/**
DB_PRIMOS.sql
Esquema iniciai de la base de datos PRIMOS
Autor : PRIMOS
Versión : 1.0
**/

-- Creación de la base de datos

-- Database: db_primos

-- DROP DATABASE db_primos;

CREATE DATABASE db_primos
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Colombia.1252'
    LC_CTYPE = 'Spanish_Colombia.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

COMMENT ON DATABASE db_primos
    IS 'Base de datos para la aplicación de Primos';
	
/* Creación de las tablas Maestras */

/* Creación de las tablas del Modelo */

	
/* Creación de las tablas Maestras */

/* Creación de las tablas del Modelo */

-- TABLA DE CATALOGOS DEL APLICATIVO
CREATE TABLE CATALOGOS
(
    IDCATALOGO 			SERIAL  		NOT NULL,
    NOMBRECATALOGO 		VARCHAR(30)		NOT NULL,
    IDCATALOGOITEM 		INTEGER 		NOT NULL,
    ITEMCATALOGO 		VARCHAR(100)	NOT NULL,
    LOCALIZACION  		VARCHAR(2) 		NOT NULL,
    DESCRIPCION  		VARCHAR(100),
    CONSTRAINT PK_CATALOGOS PRIMARY KEY(IDCATALOGO),
	CONSTRAINT UNIQUE_CATALOG UNIQUE (NOMBRECATALOGO, IDCATALOGOITEM, ITEMCATALOGO, LOCALIZACION)
);

-- TABLA PERSONA
CREATE TABLE PERSONA(
	IDPERSONA 			SERIAL 		NOT NULL,
    STRNUMERODOCUMENTO 	VARCHAR(50) NOT NULL,
    STRNOMBRE 			VARCHAR(80) NOT NULL,
    STRAPELLIDO 		VARCHAR(80) NOT NULL,
    BITACTIVO 			BOOLEAN 	NOT NULL,
    DTMFECHACREACION 	DATE 		NOT NULL,
    CONSTRAINT PK_PERSONA PRIMARY KEY(IDPERSONA)
);

-- TABLA USUARIO
CREATE TABLE USUARIO(
	IDUSUARIO 		SERIAL		NOT NULL,
    IDPERSONA 		INTEGER		NOT NULL	REFERENCES PERSONA(IDPERSONA),
    STRUSUARIO 		VARCHAR(30)	NOT NULL,
    STRPASSWORD 	VARCHAR(50) NOT NULL,
    INTNUMINTENTOS 	INT 		NOT NULL,
    BITACTIVO 		BOOLEAN 	NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY(IDUSUARIO)
);

-- TABLA CORREO
CREATE TABLE CORREO(
	IDCORREO 	SERIAL 		NOT NULL,
    IDPERSONA 	INTEGER		NOT NULL	REFERENCES PERSONA(IDPERSONA),
    STRCORREO 	VARCHAR(30) NOT NULL,
    BITPRIMARIO BOOLEAN 	NOT NULL,
    BITACTIVO 	BOOLEAN 	NOT NULL,
    CONSTRAINT PK_CORREO PRIMARY KEY(IDCORREO)
);

-- TABLA DIRECCION
CREATE TABLE DIRECCION(
	IDDIRECCION		SERIAL 		NOT NULL,
    IDPERSONA 		INTEGER		NOT NULL	REFERENCES PERSONA(IDPERSONA),
    TIPODIRECCION	INTEGER		NOT NULL,
    STRDIRECCION	VARCHAR(30)	NOT NULL,
    BITPRIMARIO 	BOOLEAN 	NOT NULL,
    BITACTIVO 		BOOLEAN 	NOT NULL,
    CONSTRAINT PK_DIRECCION PRIMARY KEY(IDDIRECCION)
);

-- TABLA TELEFONO
CREATE TABLE TELEFONO(
	IDTELEFONO 	SERIAL 		NOT NULL,
    IDPERSONA 	INTEGER 	NOT NULL	REFERENCES PERSONA(IDPERSONA),
    TIPOTELEFO 	INTEGER 	NOT NULL,
    STRTELEFONO VARCHAR(30) NOT NULL,
    BITPRIMARIO BOOLEAN 	NOT NULL,
    BITACTIVO 	BOOLEAN 	NOT NULL,
    CONSTRAINT PK_TELEFONO PRIMARY KEY(IDTELEFONO)
);